Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
#answer1:
import numpy as np
arr=np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
list_1=[]
print("list_1")
for i in range(5):
    a=input()
    list_1.append(a)
list_2=[]
print("list_2")
for i in range(5):
    b=input()
    list_2.append(b)
a_list=np.array(list_1)
print("sorted list_1: ", np.sort(a_list))
b_list=np.array(list_2)
print("sorted list_2: ", np.sort(b_list))
print("concatenated list: ", np.concatenate((a_list, b_list)))

list_1
1
2
6
8
1
list_2
0
3
5
2
8
sorted list_1:  ['1' '1' '2' '6' '8']
sorted list_2:  ['0' '2' '3' '5' '8']
concatenated list:  ['1' '2' '6' '8' '1' '0' '3' '5' '2' '8']


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
x = np.array([2, 1, 4, 3, 5])
y = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )
xdim=np.ndim(x)
print(xdim)
ydim=np.ndim(y)
print(ydim)
xs=np.size(x)
print(xs)
ys=np.size(y)
print(ys)

1
2
5
9


In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
d_1=a.shape
print(d_1)
b = np.expand_dims(a, axis=1)  
d_2=b.shape
print(d_2)
c = np.expand_dims(a, axis=0)  
d_c2=c.shape
print(d_c2)

(6,)
(6, 1)
(1, 6)


Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [6]:
a = np.array([[1,2,3],[3,5,6], [7,8,9]])
b = np.array([[4,5,6],[2,5,4], [5,6,7]])

print('Horizontal:', np.hstack((a, b)))
print('Vertical:', np.vstack((a, b)))

Horizontal: [[1 2 3 4 5 6]
 [3 5 6 2 5 4]
 [7 8 9 5 6 7]]
Vertical: [[1 2 3]
 [3 5 6]
 [7 8 9]
 [4 5 6]
 [2 5 4]
 [5 6 7]]


Questions 6:
How to get unique items and counts of unique items?

In [7]:
x=np.array([1,2,3,11,4,1,3,2,5,7,7,])
np.unique(x)

array([ 1,  2,  3,  4,  5,  7, 11])